import os
from twilio.rest import Client

TWILIO_PHONE_NUMBER = os.environ['TWILIO_PHONE_NUMBER']
PERSONAL_PHONE_NUMBER = os.environ['PERSONAL_PHONE_NUMBER']
TWILIO_ACCOUNT_SID = os.environ['TWILIO_ACCOUNT_SID']
TWILIO_AUTH_TOKEN = os.environ['TWILIO_AUTH_TOKEN']
CLIENT = Client(TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN)
BASE_URL = 'http://localhost:5000'